"""empty message

Revision ID: bd069d50ed79
Revises: a948f95c185f
Create Date: 2023-02-01 13:11:25.169393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd069d50ed79'
down_revision = 'a948f95c185f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_constraint('register_user_token_fkey', type_='foreignkey')
        batch_op.drop_column('user_token')
        batch_op.drop_column('g_auth_verify')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('g_auth_verify', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('register_user_token_fkey', 'user', ['user_token'], ['token'])

    # ### end Alembic commands ###
